# Gnuplot script for ABCD calibration discovery visualization
#
# Reads per-algorithm .dat files generated by discover_ranges.py
# Each .dat file has columns: N  TIME_PER_POINT_US  SPEEDUP

set style line 80 lt rgb "#808080"
set style line 81 lt 0
set style line 81 lt rgb "#808080"
set grid back linestyle 81
set border 3 back linestyle 80
set xtics nomirror
set ytics nomirror

# Color palette for 14 algorithms
set style line 1  lt rgb "#000000" lw 2 pt 7  ps 0.5  # TRIVIAL - black
set style line 2  lt rgb "#E41A1C" lw 2 pt 5  ps 0.8  # STRAUSS - red
set style line 3  lt rgb "#FF7F00" lw 1 pt 6  ps 0.5  # PIPPENGER_1 - orange
set style line 4  lt rgb "#FFD700" lw 1 pt 8  ps 0.5  # PIPPENGER_2 - gold
set style line 5  lt rgb "#A6D854" lw 1 pt 10 ps 0.5  # PIPPENGER_3 - yellow-green
set style line 6  lt rgb "#4DAF4A" lw 2 pt 12 ps 0.8  # PIPPENGER_4 - green
set style line 7  lt rgb "#377EB8" lw 2 pt 4  ps 0.8  # PIPPENGER_5 - blue
set style line 8  lt rgb "#984EA3" lw 2 pt 3  ps 0.8  # PIPPENGER_6 - purple
set style line 9  lt rgb "#A65628" lw 1 pt 1  ps 0.5  # PIPPENGER_7 - brown
set style line 10 lt rgb "#F781BF" lw 1 pt 2  ps 0.5  # PIPPENGER_8 - pink
set style line 11 lt rgb "#66C2A5" lw 1 pt 9  ps 0.5  # PIPPENGER_9 - teal
set style line 12 lt rgb "#FC8D62" lw 1 pt 11 ps 0.5  # PIPPENGER_10 - salmon
set style line 13 lt rgb "#8DA0CB" lw 1 pt 13 ps 0.5  # PIPPENGER_11 - light blue
set style line 14 lt rgb "#E78AC3" lw 2 pt 7  ps 0.8  # PIPPENGER_12 - magenta

set key outside right top
set logscale x
set mxtics 10

# Graph 1: Per-point time for all algorithms
set title "Per-point time: all ecmult\\_multi algorithms"
set xlabel "Batch size (n points)"
set ylabel "Time per point (us)"
set term png size 1200,800
set output 'per_point_time.png'

plot \
    "trivial.dat"      using 1:2 with linespoints title "TRIVIAL"      ls 1, \
    "strauss.dat"      using 1:2 with linespoints title "STRAUSS"      ls 2, \
    "pippenger_1.dat"  using 1:2 with linespoints title "PIPPENGER\\_1"  ls 3, \
    "pippenger_2.dat"  using 1:2 with linespoints title "PIPPENGER\\_2"  ls 4, \
    "pippenger_3.dat"  using 1:2 with linespoints title "PIPPENGER\\_3"  ls 5, \
    "pippenger_4.dat"  using 1:2 with linespoints title "PIPPENGER\\_4"  ls 6, \
    "pippenger_5.dat"  using 1:2 with linespoints title "PIPPENGER\\_5"  ls 7, \
    "pippenger_6.dat"  using 1:2 with linespoints title "PIPPENGER\\_6"  ls 8, \
    "pippenger_7.dat"  using 1:2 with linespoints title "PIPPENGER\\_7"  ls 9, \
    "pippenger_8.dat"  using 1:2 with linespoints title "PIPPENGER\\_8"  ls 10, \
    "pippenger_9.dat"  using 1:2 with linespoints title "PIPPENGER\\_9"  ls 11, \
    "pippenger_10.dat" using 1:2 with linespoints title "PIPPENGER\\_10" ls 12, \
    "pippenger_11.dat" using 1:2 with linespoints title "PIPPENGER\\_11" ls 13, \
    "pippenger_12.dat" using 1:2 with linespoints title "PIPPENGER\\_12" ls 14

# Graph 2: Speedup vs individual ecmult (all algorithms)
set title "Speedup over individual ecmult: all algorithms"
set ylabel "Speedup (x)"
set output 'speedup_vs_individual.png'

plot \
    "strauss.dat"      using 1:3 with linespoints title "STRAUSS"      ls 2, \
    "pippenger_1.dat"  using 1:3 with linespoints title "PIPPENGER\\_1"  ls 3, \
    "pippenger_2.dat"  using 1:3 with linespoints title "PIPPENGER\\_2"  ls 4, \
    "pippenger_3.dat"  using 1:3 with linespoints title "PIPPENGER\\_3"  ls 5, \
    "pippenger_4.dat"  using 1:3 with linespoints title "PIPPENGER\\_4"  ls 6, \
    "pippenger_5.dat"  using 1:3 with linespoints title "PIPPENGER\\_5"  ls 7, \
    "pippenger_6.dat"  using 1:3 with linespoints title "PIPPENGER\\_6"  ls 8, \
    "pippenger_7.dat"  using 1:3 with linespoints title "PIPPENGER\\_7"  ls 9, \
    "pippenger_8.dat"  using 1:3 with linespoints title "PIPPENGER\\_8"  ls 10, \
    "pippenger_9.dat"  using 1:3 with linespoints title "PIPPENGER\\_9"  ls 11, \
    "pippenger_10.dat" using 1:3 with linespoints title "PIPPENGER\\_10" ls 12, \
    "pippenger_11.dat" using 1:3 with linespoints title "PIPPENGER\\_11" ls 13, \
    "pippenger_12.dat" using 1:3 with linespoints title "PIPPENGER\\_12" ls 14

# Graph 3: Winner-only speedup with crossover annotations
# Only plots algorithms that are optimal at some batch size.
# Crossover lines and labels are auto-generated by discover_ranges.py.
set title "Optimal algorithm selection: speedup over individual ecmult"
set ylabel "Speedup (x)"
set output 'winners_speedup.png'

# Load crossover annotations (vertical lines + labels)
load 'crossover_annotations.gp'

# Load winner-only plot command (auto-generated, uses same ls numbers for color consistency)
load 'winners_plot.gp'

# Clean up annotations for subsequent plots
unset arrow
unset label
